"""add cfg node columns

Revision ID: c2e6a9b6be94
Revises: 871f4d524e3d
Create Date: 2026-05-10 14:25:55.049757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2e6a9b6be94'
down_revision = '871f4d524e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_class',
    sa.Column('ms_class_id', sa.String(length=255), nullable=False),
    sa.Column('ms_class_grade', sa.String(length=10), nullable=True),
    sa.Column('ms_class_major', sa.String(length=100), nullable=True),
    sa.Column('ms_class_class', sa.String(length=10), nullable=True),
    sa.Column('ms_class_teacher', sa.String(length=100), nullable=True),
    sa.Column('ms_class_description', sa.String(length=255), nullable=True),
    sa.Column('ms_class_total_hour', sa.String(length=10), nullable=True),
    sa.Column('createdby', sa.String(length=255), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('updatedby', sa.String(length=255), nullable=True),
    sa.Column('updated', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('ms_class_id')
    )
    op.create_index(op.f('ix_ms_class_ms_class_id'), 'ms_class', ['ms_class_id'], unique=False)
    op.alter_column('ms_cfg_edge', 'ms_id_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_cfg_edge', 'ms_id_start_node',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_cfg_edge', 'ms_id_finish_node',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_cfg_edge', 'ms_label',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_cfg_edge', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_cfg_edge', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_cfg_edge', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_cfg_edge', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_cfg_node', 'ms_id_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_cfg_node', 'ms_line_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ms_cfg_node', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_cfg_node', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_cfg_node', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_cfg_node', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_modul_parameter', 'ms_id_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_modul_parameter', 'ms_nama_parameter',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_modul_parameter', 'ms_tipe_data',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ms_modul_parameter', 'ms_rules',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('ms_modul_parameter', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_modul_parameter', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_modul_parameter', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_modul_parameter', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_modul_program', 'ms_jenis_modul',
               existing_type=mysql.ENUM('F', 'P'),
               nullable=True,
               existing_server_default=sa.text("'F'"))
    op.alter_column('ms_modul_program', 'ms_nama_modul',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('ms_modul_program', 'ms_deskripsi_modul',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('ms_modul_program', 'ms_class_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_modul_program', 'ms_function_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_modul_program', 'ms_jml_parameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ms_modul_program', 'ms_tingkat_kesulitan',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_modul_program', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_modul_program', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_modul_program', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_modul_program', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_student', 'isactive',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=True,
               existing_server_default=sa.text("'Y'"))
    op.alter_column('ms_student', 'ms_student_nim',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ms_student', 'ms_student_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_student', 'ms_student_kelas',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_student', 'ms_student_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_student', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_student', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_student', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_student', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_system', 'ms_system_value',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_system', 'isactive',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=True,
               existing_server_default=sa.text("'Y'"))
    op.alter_column('ms_system', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_system', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_system', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_system', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_teacher', 'ms_teacher_kode_dosen',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('ms_teacher', 'ms_teacher_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_teacher', 'isactive',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=True,
               existing_server_default=sa.text("'Y'"))
    op.alter_column('ms_teacher', 'ms_teacher_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_teacher', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_teacher', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_teacher', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_teacher', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_topik_modul', 'ms_id_topik',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_topik_modul', 'ms_id_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_topik_modul', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_topik_modul', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_topik_modul', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_topik_modul', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_topik_pengujian', 'status',
               existing_type=mysql.ENUM('D', 'P'),
               nullable=True,
               existing_server_default=sa.text("'D'"))
    op.alter_column('ms_topik_pengujian', 'ms_nama_topik',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ms_topik_pengujian', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_topik_pengujian', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_topik_pengujian', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_topik_pengujian', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_cfg_edge', 'tr_id_topik_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tr_cfg_edge', 'tr_id_student',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tr_cfg_edge', 'tr_status',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=True,
               existing_server_default=sa.text("'N'"))
    op.alter_column('tr_cfg_edge', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_cfg_edge', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_cfg_edge', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_cfg_edge', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_tr_cfg_edge_tr_id_student', table_name='tr_cfg_edge')
    op.drop_index('ix_tr_cfg_edge_tr_id_topik_modul', table_name='tr_cfg_edge')
    op.alter_column('tr_cfg_node', 'tr_id_topik_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False
               )
    op.alter_column('tr_cfg_node', 'tr_id_student',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tr_cfg_node', 'tr_status',
               existing_type=mysql.ENUM('Y', 'N', 'S'),
               nullable=True,
               existing_server_default=sa.text("'N'"))
    op.alter_column('tr_cfg_node', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_cfg_node', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_cfg_node', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_cfg_node', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('ix_tr_cfg_node_tr_id_student', table_name='tr_cfg_node')
    op.drop_index('ix_tr_cfg_node_tr_id_topik_modul', table_name='tr_cfg_node')
    op.alter_column('tr_penyelesaian_modul', 'tr_tgl_mulai',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('tr_penyelesaian_modul', 'tr_status_eksekusi',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=True,
               existing_server_default=sa.text("'N'"))
    op.alter_column('tr_penyelesaian_modul', 'tr_status_penyelesaian',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=True,
               existing_server_default=sa.text("'N'"))
    op.alter_column('tr_penyelesaian_modul', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_penyelesaian_modul', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_penyelesaian_modul', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_penyelesaian_modul', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_test_case_modul', 'tr_id_topik_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tr_test_case_modul', 'tr_student_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tr_test_case_modul', 'tr_object_pengujian',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('tr_test_case_modul', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_test_case_modul', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_test_case_modul', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_test_case_modul', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tr_test_case_modul', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_test_case_modul', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_test_case_modul', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_test_case_modul', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_test_case_modul', 'tr_object_pengujian',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('tr_test_case_modul', 'tr_student_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tr_test_case_modul', 'tr_id_topik_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tr_penyelesaian_modul', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_penyelesaian_modul', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_penyelesaian_modul', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_penyelesaian_modul', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_penyelesaian_modul', 'tr_status_penyelesaian',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=False,
               existing_server_default=sa.text("'N'"))
    op.alter_column('tr_penyelesaian_modul', 'tr_status_eksekusi',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=False,
               existing_server_default=sa.text("'N'"))
    op.alter_column('tr_penyelesaian_modul', 'tr_tgl_mulai',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index('ix_tr_cfg_node_tr_id_topik_modul', 'tr_cfg_node', ['tr_id_topik_modul'], unique=False)
    op.create_index('ix_tr_cfg_node_tr_id_student', 'tr_cfg_node', ['tr_id_student'], unique=False)
    op.alter_column('tr_cfg_node', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_cfg_node', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_cfg_node', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_cfg_node', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_cfg_node', 'tr_status',
               existing_type=mysql.ENUM('Y', 'N', 'S'),
               nullable=False,
               existing_server_default=sa.text("'N'"))
    op.alter_column('tr_cfg_node', 'tr_id_student',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tr_cfg_node', 'tr_id_topik_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index('ix_tr_cfg_edge_tr_id_topik_modul', 'tr_cfg_edge', ['tr_id_topik_modul'], unique=False)
    op.create_index('ix_tr_cfg_edge_tr_id_student', 'tr_cfg_edge', ['tr_id_student'], unique=False)
    op.alter_column('tr_cfg_edge', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_cfg_edge', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_cfg_edge', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('tr_cfg_edge', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('tr_cfg_edge', 'tr_status',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=False,
               existing_server_default=sa.text("'N'"))
    op.alter_column('tr_cfg_edge', 'tr_id_student',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tr_cfg_edge', 'tr_id_topik_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_topik_pengujian', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_topik_pengujian', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_topik_pengujian', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_topik_pengujian', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_topik_pengujian', 'ms_nama_topik',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_topik_pengujian', 'status',
               existing_type=mysql.ENUM('D', 'P'),
               nullable=False,
               existing_server_default=sa.text("'D'"))
    op.alter_column('ms_topik_modul', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_topik_modul', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_topik_modul', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_topik_modul', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_topik_modul', 'ms_id_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_topik_modul', 'ms_id_topik',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_teacher', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_teacher', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_teacher', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_teacher', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_teacher', 'ms_teacher_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_teacher', 'isactive',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=False,
               existing_server_default=sa.text("'Y'"))
    op.alter_column('ms_teacher', 'ms_teacher_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_teacher', 'ms_teacher_kode_dosen',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ms_system', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_system', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_system', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_system', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_system', 'isactive',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=False,
               existing_server_default=sa.text("'Y'"))
    op.alter_column('ms_system', 'ms_system_value',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_student', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_student', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_student', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_student', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_student', 'ms_student_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_student', 'ms_student_kelas',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_student', 'ms_student_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_student', 'ms_student_nim',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('ms_student', 'isactive',
               existing_type=mysql.ENUM('Y', 'N'),
               nullable=False,
               existing_server_default=sa.text("'Y'"))
    op.alter_column('ms_modul_program', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_modul_program', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_modul_program', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_modul_program', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_modul_program', 'ms_tingkat_kesulitan',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_modul_program', 'ms_jml_parameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ms_modul_program', 'ms_function_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_modul_program', 'ms_class_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_modul_program', 'ms_deskripsi_modul',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('ms_modul_program', 'ms_nama_modul',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ms_modul_program', 'ms_jenis_modul',
               existing_type=mysql.ENUM('F', 'P'),
               nullable=False,
               existing_server_default=sa.text("'F'"))
    op.alter_column('ms_modul_parameter', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_modul_parameter', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_modul_parameter', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_modul_parameter', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_modul_parameter', 'ms_rules',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('ms_modul_parameter', 'ms_tipe_data',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ms_modul_parameter', 'ms_nama_parameter',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_modul_parameter', 'ms_id_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_cfg_node', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_cfg_node', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_cfg_node', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_cfg_node', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_cfg_node', 'ms_line_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ms_cfg_node', 'ms_id_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_cfg_edge', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_cfg_edge', 'updatedby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_cfg_edge', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ms_cfg_edge', 'createdby',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('ms_cfg_edge', 'ms_label',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_cfg_edge', 'ms_id_finish_node',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_cfg_edge', 'ms_id_start_node',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ms_cfg_edge', 'ms_id_modul',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_ms_class_ms_class_id'), table_name='ms_class')
    op.drop_table('ms_class')
    # ### end Alembic commands ###
