@startuml

skinparam class {
    BackgroundColor #DAE8FC
    BorderColor #6C8EBF
    FontColor Black
    ArrowColor #6C8EBF
    AttributeFontColor Black
    StereotypeFontColor Black
}

class WorkerApp {
    +main()
    +setupRoutes()
}

class ExecutionService {
    -launcher : Launcher
    +runTest()
    +compileOnly()
}

class InMemoryCompiler {
    -compiler : JavaCompiler
    -standardFileManager : StandardJavaFileManager
    +compile()
}

class DynamicClassLoader {
    -classBytecode : Map
    -runtime : IRuntime
    #findClass()
}

WorkerApp --> ExecutionService : menggunakan
ExecutionService ..> InMemoryCompiler : memanggil compile()
ExecutionService --> DynamicClassLoader : menginstansiasi

@enduml